[window]
padding = { x = 2, y = 2 }
decorations = "None"
# opacity = 0.7

[font]
size = 12.0

[font.normal]
family = "Noto Sans Mono"
style = "Black"

[colors.primary]
background = "#0f1419"
foreground = "#e6e1cf"

# Ayu Theme Palette
[colors.normal]
black =   "#000000"
red =     "#ff3333"
green =   "#b8cc52"
yellow =  "#e6c446"
blue =    "#36a3d9"
magenta = "#f07171"
cyan =    "#95e6cb"
white =   "#ffffff"

[colors.bright]
black =   "#323232"
red =     "#ff6565"
green =   "#eafe84"
yellow =  "#fff778"
blue =    "#68d4ff"
magenta = "#ffa3a3"
cyan =    "#c7fffc"
white =   "#ffffff"

[cursor]
style = "Block"
unfocused_hollow = true
